"""add option5

Revision ID: a68f24543dab
Revises: c95605ba8e96
Create Date: 2026-09-07 23:12:24.686132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68f24543dab'
down_revision = 'c95605ba8e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option5', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_assessments', schema=None) as batch_op:
        batch_op.drop_column('option5')

    # ### end Alembic commands ###
